// Objective-C API for talking to github.com/divan/txqr/mobile Go package.
//   gobind -lang=objc github.com/divan/txqr/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Txqr_H__
#define __Txqr_H__

@import Foundation;
#include "Universe.objc.h"


@class TxqrDecoder;

/**
 * Decoder implements txqr wrapper around protocol decoder.
 */
@interface TxqrDecoder : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
/**
 * NewDecoder creats new txqr decoder.
 */
- (instancetype)init;
// skipped field Decoder.Decoder with unsupported type: *github.com/divan/txqr/protocol.Decoder

- (NSString*)data;
- (NSData*)dataBytes;
- (BOOL)decodeChunk:(NSString*)data error:(NSError**)error;
- (BOOL)isCompleted;
- (long)progress;
- (NSString*)speed;
@end

/**
 * NewDecoder creats new txqr decoder.
 */
FOUNDATION_EXPORT TxqrDecoder* TxqrNewDecoder(void);

#endif
