
// Objective-C API for talking to the following Go packages
//
//	github.com/divan/txqr/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Txqr_FRAMEWORK_H__
#define __Txqr_FRAMEWORK_H__

#include "Txqr.objc.h"
#include "Universe.objc.h"

#endif
